### PR TITLE
fix: fix multiple weapon being instantiated on load

### PR DESCRIPTION
**Pull request by LouisAndrew**

### CODE REVIEW

**Comment by Krysenkova** [comment]
yeah, the bugs are gone, but the sound of switching weapon starts from the beginning of the scene. Can you also hear it?

**Comment by LouisAndrew** [comment]
So the "clicking" sound should not be there when the first weapon is equipped?

**Comment by Krysenkova** [comment]
correct. I suggest:  
```
if (_firstWeapon)
        {
            _firstWeapon = false;
        }
        else
        {
            SoundManager.soundManager.PlaySwitchAmmo(transform.position);
        }
```

I think the return statement has brought the bugs. Without it it should work

**Comment by LouisAndrew** [comment]
> correct. I suggest:
> 
> ```
> if (_firstWeapon)
>         {
>             _firstWeapon = false;
>         }
>         else
>         {
>             SoundManager.soundManager.PlaySwitchAmmo(transform.position);
>         }
> ```
> 
> I think the return statement has brought the bugs. Without it it should work

Ok, you got it right!

**Pull request merged**
