### PR TITLE
add timer

### PR DESCRIPTION
**Pull request by Krysenkova**
- The UI is to be replaced with better one.  Now it is just for testing.
- Time is set to 20 sec for testing purpose. Easy to configure from Inspector panel, depending on how much time we're going to give for each level

### CODE REVIEW

**Comment by hunsri** [comment]
Was the inclusion of the .vsconfig file intended?
If not I recommend adding it to the .gitignore

**Comment by Krysenkova** [comment]
Not intended, my fault. .gitignore updated

**Review by hunsri — APPROVED** [review]
Should be ok now :+1:

**Comment by hunsri** [comment]
Just noticed there was another file "UpgradeLog.htm"  which I missed
I suppose that one wasn't meant to land in here as well

Since I merged it onto the main branch I deleted it there.

**Pull request merged**
