### PR TITLE
feat: integrate npc healthbar with shooting functionality

### PR DESCRIPTION
**Pull request by LouisAndrew**
Features: 
- Integrate NPC-Healthbar (PR #7 ) with the shooting functionality
- Set `DemoPlayer`, `Enemy`, and `CrosshairCanvas` as prefab

Open question:
- NPC Healthbar: Are we going to decrease the health or actually increase the health of the npc when we shoot them ? 🤔

### CODE REVIEW

**Comment by phnyn** [comment]
I think increase for everyone 🤔
- infected ones maybe should start with a health of 0%? and then when we shoot them it increases little by little 
- normal ones with mask: maybe start at like 60-75% and then once we vaccinate them it'll slowly go up to 100%?
- normal ones without mask: maybe start health at 50% and just increase by 10% when we throw masks at them

**Comment by LouisAndrew** [comment]
Alright. Will push the change a little bit later

**Comment by LouisAndrew** [comment]
Okay, it's done. Changed some line from your PR @phnyn if that's okay for you

**Review by hunsri — APPROVED** [review]
Works :+1:

**Pull request merged**
