### PR TITLE
feat: comply to naming convention and import syringe as weapon

### PR DESCRIPTION
**Pull request by LouisAndrew**

### CODE REVIEW

**Comment by hunsri** [comment]
Not sure what it is, but something in this seems to break the project, at least for me.
Could be on my end, but I'll have to close this

**Comment by LouisAndrew** [comment]
Any screenshot or log messages?

**Comment by hunsri** [comment]
**Of course!**

Auswahl_001
Auswahl_002
Auswahl_003

The missing variable could be my fault though. Probably made a resolving mistake. But I can't explain the rest.

**Comment by LouisAndrew** [comment]
Linked issue: https://community.gamedev.tv/t/error-cs0619-unity-component-camera-is-obsolete/3697/5

**Comment by LouisAndrew** [comment]
Okay. will do a patch in a new branch

**Pull request closed without merging**
