### PR TITLE
Ft/healthbar infection

### PR DESCRIPTION
**Pull request by phnyn**
**Scene:** `PlayerHealthIntegration`

**Info:**
DemoPlayer needs to have a capsule collider, EnemyHealth.cs and PlayerHealth.cs assigned to them. 
NPCs are wDefaultNPC or mDefaultNPC

**Added:**
- functionality behind the player healthbar
- different spreading rates for when npc has no mask, surgical or ffp (not used yet)
- BehaviorGetter in NPCBehavior
- Enum MaskTypes (for later use(?) and integrated it into PlayerHealth.cs (auskommentiert))
- Game UI as prefab (Healthbar, Timer, Crosshair)

**Additional Fixes:**
- adjusted the indicator of the NPCwithAccessoires so it stops wobbling around
- reorganized some files in prefabs & scenes into folders

**Bugs**, I have noticed but don't know how to quite fix:

- [x] npc healthbar seems to disappear sometimes on the green background (?)
- [ ] npcs sometimes walk into objects weirdly 
- [ ]  npcs jump over objects and eachother 
- [ ] npc walks through pillar
- [ ] npc walks on the same place

### CODE REVIEW

**Comment by LouisAndrew** [comment]
You can fix the health bar not showing on certain parts by setting the `Order In Layer` on the `Healthstatus` canvas within the prefab to 99 

Screenshot 2021-07-04 at 14 47 54

**Comment by LouisAndrew** [comment]
Found a bug: NPC walks through a pillar. But we can worry about that later

Screenshot 2021-07-04 at 14 37 57

**Comment by LouisAndrew** [comment]
The marker sphere (indicator) also doesn't show up on some cases. It would be really nice if you could add this snippet in the `NPCBehavior`'s `Awake` method

```
_indicator.GetComponent<Renderer>().sortingOrder = 99;
```

**Comment by phnyn** [comment]
Could you try using the npcs from the NPCwithAccessoires folder?

**Comment by LouisAndrew** [comment]
> Could you try using the npcs from the NPCwithAccessoires folder?

NPCs have the same problems. If those are fixed, they should work perfectly.

**Comment by LouisAndrew** [comment]
Would suggest to increase the infection probability in the future (seen that the current one is just for testing only). Tried to spawn 100 infected(s) and it takes quite a long time to get fully infected.

**Comment by phnyn** [comment]
Yeah it's pretty slow but the probability is already at 90%. I guess the npcs have to walk faster again? Though right now the player has to collide with 10 infected people to be fully infected

**Comment by LouisAndrew** [comment]
@phnyn Could you do a quick test on Default Animated NPC. If it works we can merge this

**Comment by phnyn** [comment]
I could also maybe move the npcBorders a bit to make the space a bit smaller?

**Comment by LouisAndrew** [comment]
There's a conflict. Maybe you could revert the commit, pull latest changes, then reapply the commit.

**Comment by phnyn** [comment]
I don't think it's working I'll just try making a new branch

**Comment by LouisAndrew** [comment]
You could run `git cherry-pick 2ca0699dae5cecd012eaaba0e7ff231e13eac0a4` to reapply your commit `Added box collider to 'säulen'` on top of the branch

**Comment by phnyn** [comment]
I use SourceTree so :( but the Spawner doesn't work anymore for me
Edit: Okay should work again

**Comment by LouisAndrew** [comment]
Now it works on my side. But the spawner doesn't spawn until some amount of time. I guess this was not the case before?

**Comment by phnyn** [comment]
No it spawned almost immediately. Not sure what would be causing that though

**Comment by LouisAndrew** [comment]
Ok. Also no idea. I would say we can merge this PR but still keep the branch open for the bug fixes. Wdyt?

**Comment by phnyn** [comment]
Sure!

**Review by LouisAndrew — APPROVED** [review]

**Pull request merged**
