### PR TITLE
feat: add animation for ffp2 masks

### PR DESCRIPTION
**Pull request by LouisAndrew**

### CODE REVIEW

**Comment by LouisAndrew** [comment]
Same exact animation, but for ffp2 mask

**Comment by hunsri** [comment]
The hand appears to be too near to the camera, so there are parts that are not displayed

Auswahl_003
Auswahl_004

**Comment by LouisAndrew** [comment]
Indeed there are a problem for the hand positioning by FFP2 weapon, but the problem isn't actually that it's too close to the camera. Are you sure you don't have any weapon loaded in the screen before loading the game?

https://user-images.githubusercontent.com/61015467/124166262-e404a980-daa2-11eb-9b51-b65591641743.mp4

**Comment by LouisAndrew** [comment]
> The hand appears to be too near to the camera, so there are parts that are not displayed
> 
> Auswahl_003
> Auswahl_004

Just realized that this could really be my fault. Changed the `WeaponHolder` positioning globally now (could be seen inside `DemoPlayer` prefab).

- Added weapon names to the `WeaponName` text field
- Fix race condition where the `WeaponHolder` is trying to access `PlayerDataManager` before its `Start()` method is not finished yet
- Add animation when the ammo drops on mask weapons (see attachment)


https://user-images.githubusercontent.com/61015467/124283438-3221b780-db4c-11eb-9f68-42f29473fd41.mov

**Comment by LouisAndrew** [comment]
DemoPlayer is in `/Prefabs/Player` folder. All other `DemoPlayer` prefabs could be deleted.

**Comment by hunsri** [comment]
**Yep, the glitch is gone.** But one last thing:
Noticed that the masks are always pointing the same way in relation to the world axis.
This makes it hard to see at certain angles. For that reason I would also slow down the velocity of the masks.
I suggest we copy the orientation of the player for the masks so that they are aligned to the player instead of the world.

**Comment by LouisAndrew** [comment]
> **Yep, the glitch is gone.** But one last thing:
> Noticed that the masks are always pointing the same way in relation to the world axis.
> This makes it hard to see at certain angles. For that reason I would also slow down the velocity of the masks.
> I suggest we copy the orientation of the player for the masks so that they are aligned to the player instead of the world.

Resolved with the last commit. 
**One drawback to keep in mind:** By changing the projectile speed (*velocity of the masks*) it would also make the mask a bit more "prone" to gravity. Meaning long range shooting would be more difficult.

**Comment by hunsri** [comment]
> it would also make the mask a bit more "prone" to gravity

We could let the mask prefab ignore the gravity.
But I think it looks better with a ballistic curve, I think we can keep it how it is.

**Comment by LouisAndrew** [comment]
> > it would also make the mask a bit more "prone" to gravity
> 
> We could let the mask prefab ignore the gravity.
> But I think it looks better with a ballistic curve, I think we can keep it how it is.

Yes, let's keep it as it is. Just a heads up

**Review by hunsri — APPROVED** [review]

**Pull request merged**
