### PR TITLE
Ft/player animations

### PR DESCRIPTION
**Pull request by LouisAndrew**
- add player animation to the weapon
- change the entire player model to just display hands -> **We are implementing the game as a VR anyway (most of VR games actually implement just hands as player model on their games [link](https://www.youtube.com/watch?v=TVPIDVdcqg0&ab_channel=BMFVR) )** 
- Add fire rate to shooting system
- Add `defaultPosition` attribute to `WeaponData`

### CODE REVIEW

**Comment by hunsri** [comment]
I think the weapon fire animation looks a bit odd
Maybe you could make it look like the recoil from a shotgun?

That the weapon including the hand holding it gets punched back

[A bit like in this video here :D](https://youtu.be/cE3DdYeNDOY)

**Comment by LouisAndrew** [comment]
The hand is going to be the player's hand (the controller, how they interact with the game). You sure we want to animate the hand?

**Comment by hunsri** [comment]
We could use something that just looks like the players hand
Would probably help with VR integration too

**Comment by LouisAndrew** [comment]
what do you mean by "looks like a player's hand"?

Would tweak the animation to maybe make it look better but I'm not sure about animating the hand as it would move as the user's hand moves

**Comment by hunsri** [comment]
> what do you mean by "looks like a player's hand"?

I meant that we could make the real hand invisible and create a new hand. That one we could then animate (by scripts or animator) to bounce back a bit after each shot

**Comment by LouisAndrew** [comment]
- Move hand as a child of weapon
- Create equip animation
- Remove fire rate, as animation now "determines" the fire rate
- Tweak shooting animation

**Pull request closed without merging**
