### PR TITLE
Ft/set particles

### PR DESCRIPTION
**Pull request by Krysenkova**
I called the branch "set particles", but actually here is the background music fix in train station and particles.

### CODE REVIEW

**Comment by LouisAndrew** [comment]
Any scene to test?

**Comment by LouisAndrew** [comment]
TrainStation works, by the way

**Comment by Krysenkova** [comment]
It should be possible to test in a parkwithhealthbar scene

**Comment by LouisAndrew** [comment]
ok it works

**Review by LouisAndrew — APPROVED** [review]

**Comment by LouisAndrew** [comment]
Hey @Krysenkova, is it okay for you if I revert the merge? Seems like you merged main into the branch and reverted it. Changes made on main between the timestamps where you created the branch and merged it are missing.

**Comment by LouisAndrew** [comment]
Didn't realized it before, my bad.

**Comment by Krysenkova** [comment]
@LouisAndrew that's ok, of course revert it

**Comment by LouisAndrew** [comment]
Thanks! Please reapply the changes on top of the current `main` :)

**Comment by Krysenkova** [comment]
ok!

**Pull request merged**
