### PR TITLE
added animated NPC

### PR DESCRIPTION
**Pull request by hunsri**
Description says it all, added a new DefaultNPC that is animated.

Example Scene: `NPCAnimation`

### CODE REVIEW

**Comment by LouisAndrew** [comment]
What is actually the difference between infected and uninfected other than the speed? How can player identifies which is which other than their speed and the indicator on minimap?

**Comment by phnyn** [comment]
> What is actually the difference between infected and uninfected other than the speed? How can player identifies which is which other than their speed and the indicator on minimap?

It's the bubble on their heads!

**Comment by LouisAndrew** [comment]
Setting the `IsInfected` prop on `PlayerHealth` doesn't change the bubble on their head?


https://user-images.githubusercontent.com/61015467/123942198-3195ef00-d99b-11eb-914b-db72a2452651.mov

**Comment by phnyn** [comment]
> Setting the `IsInfected` prop on `PlayerHealth` doesn't change the bubble on their head?
> 
>  Screen.Recording.2021-06-30.at.12.02.11.mov

This is just the default NPC with walking animation - the infection and all that happens in the npc behaviour feature. I don't think it's connected with the enemy health in any way yet

**Comment by LouisAndrew** [comment]
For me it's not happening also in the npc behavior. Is it a problem on my side?

https://user-images.githubusercontent.com/61015467/123943303-5048b580-d99c-11eb-90b1-ae7a1109ffb9.mp4

**Comment by phnyn** [comment]
You need to add another NPCSpawner with an infected person

**Comment by LouisAndrew** [comment]
> You need to add another NPCSpawner with an infected person

I see. Okay thanks!

**Review by LouisAndrew — APPROVED** [review]

**Pull request merged**
