### PR TITLE
Ft/trainstation

### PR DESCRIPTION
**Pull request by phnyn**
Please check if this works! 
We also have the option to add more posters about corona

### CODE REVIEW

**Comment by LouisAndrew** [comment]
Works on my side. Got this error when first loaded unity, but restarting unity did the trick.
image

**Comment by hunsri** [comment]
**Looks very good so far! Well done!**

Although I found a few graphic glitches when I tried it
Auswahl_005
Auswahl_006
Auswahl_008

Also I think we should remove / switch one texture since it is clearly from a copyrighted source
Auswahl_007

**Comment by phnyn** [comment]
Ah no those aren't exactly glitches that's just the standard material of the prefab. Was thinking we could replace it with some corona stuff maybe and the ticket one didn't fit the object exactly but it still looked better than just a yellow box 

I tried changing it but this is probably the best I can do
Bildschirmfoto 2021-06-25 um 01 14 35

**Comment by hunsri** [comment]
I moved a few clipping objects and edited one poster (removed the Diabetes text)

**Review by hunsri — APPROVED** [review]

**Pull request merged**
